In [1]:
import numpy as np


In [2]:
a = [1,2,3]
ndarr = np.array(a)

In [3]:
ndarr

array([1, 2, 3])

In [4]:
type(ndarr)

numpy.ndarray

In [6]:
# a = a+2
ndarr += 2
print(ndarr)

[3 4 5]


In [9]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=float)
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
print(arr2d.dtype)

float64


In [16]:
arr2di = arr2d.astype('int32')
arr2di

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(arr2d.dtype)
print(arr2di.dtype)

float64
int32


In [19]:
arr2d.astype('str')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U32')

In [20]:
a = int(input())
print(a)

213
213


In [22]:
arr_b = np.array([1,2,0,3,0,-1], dtype=bool)
arr_b

array([ True,  True, False,  True, False,  True])

In [25]:
arr_o = np.array([1, 'a', 1.2, 'asd'], dtype='object')
# 将dtype设置为object，array中可以放不同类型数据
arr_o

array([1, 'a', 1.2, 'asd'], dtype=object)

In [26]:
print(type(arr2d))
li = arr2d.tolist()
print(type(li))
li

<class 'numpy.ndarray'>
<class 'list'>


[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [27]:
print(arr2d.ndim, arr2d.dtype, arr2d.size, arr2d.shape)

2 float64 9 (3, 3)


In [31]:
print(arr2d[0, :])

[1. 2. 3.]


In [33]:
b = arr2d>4
print(b)
print(arr2d[b])

[[False False False]
 [False  True  True]
 [ True  True  True]]
[5. 6. 7. 8. 9.]


In [34]:
print(arr2d[::-1])

[[7. 8. 9.]
 [4. 5. 6.]
 [1. 2. 3.]]


In [37]:
print(arr2d[::2])
arr1d = arr2d.flatten()
print(arr1d)


[[1. 2. 3.]
 [7. 8. 9.]]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [38]:
print(arr1d[1:6:2])

[2. 4. 6.]


In [39]:
print(arr1d[-3:])

[7. 8. 9.]


In [40]:
print(arr1d[::-1])

[9. 8. 7. 6. 5. 4. 3. 2. 1.]


In [41]:
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [57]:
arr2d[1,1] = np.nan
arr2d[2,1] = np.inf
arr2d

Mean: [2. 3. 5.]
Min: -1.0
Max: [7. 2. 9.]


In [60]:
missing_positions = np.isnan(arr2d) | np.isinf(arr2d)
print(missing_positions)
arr2d[missing_positions] = -1
print(arr2d)
arr2d[1,1] = 5
arr2d[2,1] = 8
print(arr2d)

[[False False False]
 [False False False]
 [False False False]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [62]:
print(f"Mean: {arr2d.mean()}")
print(f"Min: {arr2d.min()}")
print(f"Max: {arr2d.max()}")

Mean: 5.0
Min: 1.0
Max: 9.0


In [63]:
print(np.amin(arr2d, axis=1))
print(np.amax(arr2d, axis=0))

[1. 4. 7.]
[7. 8. 9.]


In [66]:
arr = arr2d[:2, :2]
print(arr)
arr[0,0] = 10
print(arr)
print(arr2d)

[[10.  2.]
 [ 4.  5.]]
[[10.  2.]
 [ 4.  5.]]
[[10.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [69]:
arr = arr2d[:2, :2].copy()
arr[0, 0] = -10
print(arr)
print(arr2d)

[[-10.   2.]
 [  4.   5.]]
[[10.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [76]:
arr2d = np.random.rand(3,4)*10
arr2d = arr2d.astype('int')
arr2d

array([[5, 3, 4, 4],
       [0, 9, 2, 3],
       [7, 9, 4, 8]])

In [85]:
# arr2d = arr2d.reshape(4, 3)
# print(arr2d)
arr2d.reshape(4,3)

array([[5, 3, 4],
       [4, 0, 9],
       [2, 3, 7],
       [9, 4, 8]])

In [90]:
arr2d.reshape(3,4)
print(arr2d.T)

[[5 4 2 9]
 [3 0 3 4]
 [4 9 7 8]]


In [91]:
a = arr2d.flatten()
b = arr2d.ravel()
print(a)
print(b)

[5 3 4 4 0 9 2 3 7 9 4 8]
[5 3 4 4 0 9 2 3 7 9 4 8]


In [92]:
a[0] = 1
print(arr2d)

[[5 3 4]
 [4 0 9]
 [2 3 7]
 [9 4 8]]


In [93]:
b[0] = 1
print(arr2d)

[[1 3 4]
 [4 0 9]
 [2 3 7]
 [9 4 8]]


.ravel() version returns a reference to the input ndarray, like the b above

In [94]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.arange(0,14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [98]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [99]:
np.arange(10, 0, -1) # decreasing order

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [100]:
np.linspace(start=1, stop=50, num=10, dtype=int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [101]:
np.linspace(1, 50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [104]:
np.linspace(0, 100).size

50

In [105]:
# limit the number of digits
np.set_printoptions(precision=2)
np.logspace(start=1, stop=50, num=15, base=10)

array([1.00e+01, 3.16e+04, 1.00e+08, 3.16e+11, 1.00e+15, 3.16e+18,
       1.00e+22, 3.16e+25, 1.00e+29, 3.16e+32, 1.00e+36, 3.16e+39,
       1.00e+43, 3.16e+46, 1.00e+50])

In [107]:
np.logspace(start=1, stop=10, base=2, dtype=int)

array([   2,    2,    2,    2,    3,    3,    4,    4,    5,    6,    7,
          8,    9,   10,   11,   13,   15,   17,   19,   22,   25,   28,
         32,   37,   42,   48,   54,   62,   70,   80,   91,  103,  117,
        133,  151,  172,  195,  222,  252,  286,  325,  369,  420,  477,
        541,  615,  698,  793,  901, 1024])

np.tile() will repeat a whole list or array n times. Whereas np.repeat() repeats each item n times

In [111]:
a = np.array([1,2,3])
b = np.tile(a, 2)
print(b)
c = np.repeat(a, 2)
print(c)

[1 2 3 1 2 3]
[1 1 2 2 3 3]


In [112]:
# random number between [0, 1) with a shape of (2, 2)
print(np.random.rand(2,2))
# Normal distribution with mean=0 & std=1, a shape of (2, 2)
print(np.random.randn(2,2))

[[0.4  0.45]
 [0.03 0.57]]
[[-1.25  0.11]
 [ 0.49 -0.2 ]]


In [113]:
# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

# One random number between [0,1)
print(np.random.random())

# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

[[4 0]
 [0 3]]
0.7786460033163551
[[0.48 0.96]
 [0.15 0.65]]


In [116]:
# pick 10 items from an array with equal probabilities
print(np.random.choice(['h', 'e', 'l', 'l', 'o'], size=10))
# pick 10 items from an array with assigned probabilities
print(np.random.choice(['h', 'e', 'l', 'l', 'o'], size=10, p=[0.2,0.4,0.1,0.1,0.2]))

['o' 'e' 'l' 'l' 'l' 'e' 'e' 'h' 'e' 'e']
['h' 'e' 'e' 'e' 'h' 'e' 'o' 'o' 'h' 'l']


In [121]:
# if you want to generate exactly same numbers every time, set the seed
rn = np.random.RandomState(100)
print(rn.rand(2, 2))

[[0.54 0.28]
 [0.42 0.84]]


In [124]:
np.random.seed(100)
print(np.random.rand(2,2))


[[0.54 0.28]
 [0.42 0.84]]
[[0.   0.12]
 [0.67 0.83]]


In [126]:
arr = np.random.randint(0, 10, size=10)
arr

array([0, 9, 6, 2, 4, 1, 5, 3, 4, 4])

In [127]:
arr[1] = 6
arr[0] = 5
print(arr)

[5 6 6 2 4 1 5 3 4 4]


In [128]:
# get the unique items
unique, count = np.unique(arr, return_counts=True)
print(unique)
print(count)

[1 2 3 4 5 6]
[1 1 1 3 2 2]


In [1]:
import numpy as np

In [4]:
arr2d = np.array([[1,2,3,], [4,5,6,],[7,8,9,]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
a, b = np.where(arr2d>4)
arr = np.where(arr2d>4)
print(arr)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))


In [10]:
c = np.vstack((a,b))
print(c)

[[1 1 2 2 2]
 [1 2 0 1 2]]


In [17]:
d = arr2d.take(arr)
print(d)

[[2 2 3 3 3]
 [2 3 1 2 3]]


In [18]:
arr1d = arr2d.flatten()

In [19]:
indexing = np.where(arr1d>5)
print(indexing)
print(arr1d.take(indexing))

(array([5, 6, 7, 8], dtype=int64),)
[[6 7 8 9]]


In [23]:
e = np.where(arr2d>4, 1, 0)
print(e)
f = arr2d>4
f = f.astype('int')
print(f)

[[0 0 0]
 [0 1 1]
 [1 1 1]]
[[0 0 0]
 [0 1 1]
 [1 1 1]]


In [24]:
# locate the max&min values
loc_max = np.argmax(arr1d)
loc_min = np.argmin(arr1d)
print(arr1d.take(loc_max))
print(arr1d.take(loc_min))

9
1


In [32]:
# TURN OFF SCIENTIFIC NOTATION
np.set_printoptions(suppress=True)

path = 'https://raw.githubusercontent.com/selva86/datasets/master/Auto.csv'
data = np.genfromtxt(path, delimiter=',', skip_header=1, filling_values=0, dtype='float')
data[:5]

array([[  18. ,    8. ,  307. ,  130. , 3504. ,   12. ,   70. ,    1. ,
           0. ],
       [  15. ,    8. ,  350. ,  165. , 3693. ,   11.5,   70. ,    1. ,
           0. ],
       [  18. ,    8. ,  318. ,  150. , 3436. ,   11. ,   70. ,    1. ,
           0. ],
       [  16. ,    8. ,  304. ,  150. , 3433. ,   12. ,   70. ,    1. ,
           0. ],
       [  17. ,    8. ,  302. ,  140. , 3449. ,   10.5,   70. ,    1. ,
           0. ]])

In [48]:
# data_with_text = np.genfromtxt(path, delimiter=',', skip_header=True, dtype='object')
# or set dtype to None
data_with_text = np.genfromtxt(path, delimiter=',', skip_header=True, dtype=None, encoding='utf-8')
print(data_with_text[:3])
print(data_with_text.dtype)


[(18., 8, 307., 130, 3504, 12. , 70, 1, '"chevrolet chevelle malibu"')
 (15., 8, 350., 165, 3693, 11.5, 70, 1, '"buick skylark 320"')
 (18., 8, 318., 150, 3436, 11. , 70, 1, '"plymouth satellite"')]
[('f0', '<f8'), ('f1', '<i4'), ('f2', '<f8'), ('f3', '<i4'), ('f4', '<i4'), ('f5', '<f8'), ('f6', '<i4'), ('f7', '<i4'), ('f8', '<U38')]


In [49]:
np.savetxt('out.csv', data, delimiter=',')

In [50]:
np.save('myarray.npy', arr2d)


In [51]:
a = np.load('myarray.npy')
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [57]:
arr = np.arange(10, 19).reshape(3,3)
v_cat = np.vstack((arr2d, arr))
print(v_cat)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [59]:
a = np.concatenate([arr2d, arr], axis=0)
b = np.r_[arr2d, arr]
print(a)
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


In [60]:
a = np.concatenate([arr2d, arr], axis=1)
b = np.hstack((arr2d, arr))
c = np.c_[arr2d, arr]
print(a)
print(b)
print(c)

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [61]:
arr = np.random.randint(1, 10, size=(8,4))
print(arr)

[[3 3 7 8]
 [5 8 6 4]
 [1 1 1 1]
 [6 8 6 6]
 [3 2 1 9]
 [9 8 1 9]
 [1 5 3 9]
 [7 7 6 7]]


In [65]:
# np.sort(arr, axis=0)

In [66]:
# np.sort(arr, axis=1)

In [72]:
pos = np.argsort(arr, axis=0)
print(pos)
# print(arr[pos])
arr1d = np.random.randint(1, 10, size=(10, ))
print(arr1d)

[[2 2 2 2]
 [6 4 4 1]
 [0 0 5 3]
 [4 6 6 7]
 [1 7 1 0]
 [3 1 3 4]
 [7 3 7 5]
 [5 5 0 6]]
[6 1 9 4 1 3 3 1 5 8]


In [73]:
pos = np.argsort(arr1d)
print(arr1d[pos])

[1 1 1 3 3 4 5 6 8 9]


In [76]:
sorted_index_1stcol = arr[:, 0].argsort()
print(sorted_index_1stcol)
print(arr[sorted_index_1stcol[::-1]])

[2 6 0 4 1 3 7 5]
[[9 8 1 9]
 [7 7 6 7]
 [6 8 6 6]
 [5 8 6 4]
 [3 2 1 9]
 [3 3 7 8]
 [1 5 3 9]
 [1 1 1 1]]


In [77]:
print(arr)

[[3 3 7 8]
 [5 8 6 4]
 [1 1 1 1]
 [6 8 6 6]
 [3 2 1 9]
 [9 8 1 9]
 [1 5 3 9]
 [7 7 6 7]]


## sort an array based on 2 or more columns
Just remember to place the column to be sorted first at the rightmost side inside the tuple.

In [79]:
lexsorted_index = np.lexsort((arr[:, 1], arr[:, 0]))
print(lexsorted_index)
print(arr[lexsorted_index])
print(arr[lexsorted_index[::-1]])

[2 6 4 0 1 3 7 5]
[[1 1 1 1]
 [1 5 3 9]
 [3 2 1 9]
 [3 3 7 8]
 [5 8 6 4]
 [6 8 6 6]
 [7 7 6 7]
 [9 8 1 9]]
[[9 8 1 9]
 [7 7 6 7]
 [6 8 6 6]
 [5 8 6 4]
 [3 3 7 8]
 [3 2 1 9]
 [1 5 3 9]
 [1 1 1 1]]


In [80]:
# np.datetime64 object
date = np.datetime64('2022-12-29 11:52:00')
print(date)

2022-12-29T11:52:00


Of course you can pass hours, minutes, seconds till nanoseconds as well. Let’s remove the time component from date64

In [95]:
dt = np.datetime64(date, 'D')
print(dt)

2022-12-29


In [93]:
# dt  = np.datetime64(date, 'Y')
# print(dt)

By default, if you add a number increases the number of days. But if you need to increase any other time unit like months, hours, seconds etc, then the timedelta object is much convenient.

In [96]:
tenminutes = np.timedelta64(10, 'm')
tenseconds = np.timedelta64(10, 's')
print('add 10 days ', dt+10)
print('add 10 minutes ', dt+tenminutes)
print('add 10 seconds ', dt+tenseconds)


add 10 days  2023-01-08
add 10 minutes  2022-12-29T00:10
add 10 seconds  2022-12-29T00:00:10


In [98]:
print(np.datetime_as_string(dt))
date_str = np.datetime_as_string(dt)
print(type(date_str))

2022-12-29
<class 'numpy.str_'>


In [100]:
# create a sequence of dates
arrDates = np.arange(np.datetime64('2022-12-29'), np.datetime64('2023-01-09'))
print(arrDates)

['2022-12-29' '2022-12-30' '2022-12-31' '2023-01-01' '2023-01-02'
 '2023-01-03' '2023-01-04' '2023-01-05' '2023-01-06' '2023-01-07'
 '2023-01-08']


In [101]:
print(np.is_busday(arrDates))

[ True  True False False  True  True  True  True  True False False]


In [104]:
# convert np.datetime64 to datetime.datetime
import datetime
dt_li = dt.tolist()
print(dt_li)
print(type(dt_li))

2022-12-29
<class 'datetime.date'>


In [111]:
def foo(x):
    if x%2==0:
        x = x/2
    elif x%2==1:
        x = x**2
    return x
x = 10
print(foo(x))

5.0


In [112]:
x = np.array([10, 11, 12, 13])
# np.vectorize()--- makes a scalar function works on vectors too
foo_v = np.vectorize(foo, otypes=[float])
print(foo_v(x))

[  5. 121.   6. 169.]


In [119]:
# apply_along_axis --- apply a function column wise or row wise
arr2d = np.random.randint(5,20, size=(4,4))
print(arr2d)

[[ 9 12 16  9]
 [17 10 17 16]
 [ 5 17  7  7]
 [19  9 13 19]]


In [123]:
a=np.max(arr2d, axis=1)
b=np.min(arr2d, axis=1)
print(a)
print(b)
print(a-b)

[16 17 17 19]
[ 9 10  5  9]
[ 7  7 12 10]


In [125]:
lst = range(10000)
probs = np.random.random(10000)
probs /= probs.sum()
# a log faster than np.random.choice
%timeit lst[np.searchsorted(probs.cumsum(), np.random.random())]
%timeit np.random.choice(lst, p=probs)

24.9 µs ± 828 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
619 µs ± 18.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [126]:
arr1d = np.random.randint(1, 10, size=(10,))
print(arr1d)

[2 2 9 7 2 8 1 9 2 2]


In [132]:
a = arr1d[:, np.newaxis, np.newaxis]
# print(a)
b = arr1d[np.newaxis, :]
print(b)

[[2 2 9 7 2 8 1 9 2 2]]


In [136]:
c = np.clip(arr1d, 4, 7)
print(c)

[4 4 7 7 4 7 4 7 4 4]


In [148]:
x = np.array([1,1,2,2,2,4,4,5,6,6,6])
bcount = np.bincount(x)
print(bcount)
counts, bins = np.histogram(x, [1, 2, 3, 4])
print(counts)
print(bins)

[0 2 3 0 2 1 3]
[2 3 2]
[1 2 3 4]


In [150]:
indexes = np.argsort(bcount)
print(indexes)
print(indexes[:3])

[0 3 5 1 4 2 6]
[0 3 5]


In [151]:
arr = np.random.randint(1, 10, size=(4, 6))
brr = np.random.randint(1, 10, size=(4, 6))
print(arr)
print(brr)

[[6 7 6 7 3 1]
 [3 9 4 5 2 4]
 [2 6 8 4 5 6]
 [4 5 4 6 9 9]]
[[4 5 8 1 5 7]
 [2 6 4 3 5 2]
 [3 2 1 2 2 2]
 [2 2 6 8 9 1]]


In [156]:
print(arr[:2, :2])
print(np.mean(arr[:2, :2]))
print(np.std(arr[:2, :2]))

[[6 7]
 [3 9]]
6.25
2.165063509461097


In [158]:
crr = np.concatenate([arr, brr],axis=0)
print(crr)

[[6 7 6 7 3 1]
 [3 9 4 5 2 4]
 [2 6 8 4 5 6]
 [4 5 4 6 9 9]
 [4 5 8 1 5 7]
 [2 6 4 3 5 2]
 [3 2 1 2 2 2]
 [2 2 6 8 9 1]]


In [6]:
import numpy as np
print(np.__version__)

1.23.1


In [10]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a = np.ones((3,3),dtype=bool)
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
b = np.full((3, 4), 100, dtype=float)
print(b)
a = np.full((3,3), True, dtype=bool)
print(a)

[[100. 100. 100. 100.]
 [100. 100. 100. 100.]
 [100. 100. 100. 100.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [20]:
a = np.arange(10)
odd_pos = np.where(a%2==1)
odds = a.take(odd_pos)
odds

array([[1, 3, 5, 7, 9]])

In [23]:
a[a%2==1]

array([1, 3, 5, 7, 9])

In [24]:
a[a % 2 == 1] = -1
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [26]:
a = np.arange(10)
b = a.copy()
b[b%2==1] = -1
print(b)
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [27]:
odds_replaced = np.where(a%2==1, -1, a)
print(odds_replaced)
print(a)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]
[0 1 2 3 4 5 6 7 8 9]


In [31]:
a = a.reshape(2, -1)
print(a)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [38]:
b = np.arange(10, 20).reshape(2, -1)
# stacked_array = np.vstack([a, b])
# stacked_array = np.concatenate([a, b], axis=0)
stacked_array = np.r_[a, b]
print(stacked_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [42]:
# h_stacked_array = np.hstack([a, b])
# h_stacked_array = np.concatenate([a, b], axis=1)
h_stacked_array = np.c_[a, b]
print(h_stacked_array)

[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


In [46]:
a = np.array([1, 2, 3])
b = np.repeat(a, 3)
b = np.concatenate([b, a, a, a])
b

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [48]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [51]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
# np.unique(a[a==b])
np.intersect1d(a, b)

array([2, 4])

In [54]:
a = np.arange(1, 6)
b = np.arange(5, 10)
np.setdiff1d(a, b)

array([1, 2, 3, 4])

In [56]:
a = np.array([1,2,3,2,3,4,3,4,5,6])  
b = np.array([7,2,10,2,7,4,9,4,9,8])
pos = np.where(a==b)
pos

(array([1, 3, 5, 7], dtype=int64),)

In [63]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
pos = np.where((a>=5) & (a<=10))
a[pos]

array([ 6,  9, 10])

In [65]:
def maxx(x, y):
    return x if x>y else y

vec_maxx = np.vectorize(maxx)
print(maxx(1, 5))
a = np.array([5, 7, 9, 8, 6, 4, 5]) 
b = np.array([6, 3, 4, 8, 9, 7, 1])
print(vec_maxx(a, b))

5
[6 7 9 8 9 7 5]


In [75]:
a = np.arange(9).reshape(3, 3)
print(a)
# swap 2 cols/rows
# a = a[:, [1,0,2]]
# a = a[[1, 0, 2], :]
# reverse all rows/cols
# a = a[::-1, :]
a = a[:, ::-1]
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [86]:
# a = np.random.random((5, 3))*5+5
a = np.random.uniform(5, 10, size=(5, 3))
print(a)

[[6.35373461 9.03232406 9.50270245]
 [5.42183531 5.65642486 6.16481308]
 [8.67365238 6.74067812 8.29570365]
 [7.62179569 5.01627999 5.90840543]
 [7.32487539 6.27710043 8.82035177]]


In [98]:
# np.set_printoptions(precision=3)
rand_arr = np.random.random((5, 3))
print(rand_arr)

[[0.032 0.253 0.189]
 [0.384 0.689 0.192]
 [0.788 0.458 0.728]
 [0.42  0.677 0.011]
 [0.125 0.327 0.466]]


In [102]:
np.set_printoptions(precision=8, suppress=True)
rand_arr = np.random.random((3, 3))/1e2
print(rand_arr)

[[0.00794523 0.00963345 0.0051907 ]
 [0.00935465 0.00052623 0.00272324]
 [0.00422601 0.00664318 0.00451765]]
