In [1]:
import numpy as np


In [2]:
a = [1,2,3]
ndarr = np.array(a)

In [3]:
ndarr

array([1, 2, 3])

In [4]:
type(ndarr)

numpy.ndarray

In [6]:
# a = a+2
ndarr += 2
print(ndarr)

[3 4 5]


In [9]:
arr2d = np.array([[1,2,3], [4,5,6], [7,8,9]], dtype=float)
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [10]:
print(arr2d.dtype)

float64


In [16]:
arr2di = arr2d.astype('int32')
arr2di

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
print(arr2d.dtype)
print(arr2di.dtype)

float64
int32


In [19]:
arr2d.astype('str')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U32')

In [20]:
a = int(input())
print(a)

213
213


In [22]:
arr_b = np.array([1,2,0,3,0,-1], dtype=bool)
arr_b

array([ True,  True, False,  True, False,  True])

In [25]:
arr_o = np.array([1, 'a', 1.2, 'asd'], dtype='object')
# 将dtype设置为object，array中可以放不同类型数据
arr_o

array([1, 'a', 1.2, 'asd'], dtype=object)

In [26]:
print(type(arr2d))
li = arr2d.tolist()
print(type(li))
li

<class 'numpy.ndarray'>
<class 'list'>


[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]

In [27]:
print(arr2d.ndim, arr2d.dtype, arr2d.size, arr2d.shape)

2 float64 9 (3, 3)


In [31]:
print(arr2d[0, :])

[1. 2. 3.]


In [33]:
b = arr2d>4
print(b)
print(arr2d[b])

[[False False False]
 [False  True  True]
 [ True  True  True]]
[5. 6. 7. 8. 9.]


In [34]:
print(arr2d[::-1])

[[7. 8. 9.]
 [4. 5. 6.]
 [1. 2. 3.]]


In [37]:
print(arr2d[::2])
arr1d = arr2d.flatten()
print(arr1d)


[[1. 2. 3.]
 [7. 8. 9.]]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [38]:
print(arr1d[1:6:2])

[2. 4. 6.]


In [39]:
print(arr1d[-3:])

[7. 8. 9.]


In [40]:
print(arr1d[::-1])

[9. 8. 7. 6. 5. 4. 3. 2. 1.]


In [41]:
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [57]:
arr2d[1,1] = np.nan
arr2d[2,1] = np.inf
arr2d

Mean: [2. 3. 5.]
Min: -1.0
Max: [7. 2. 9.]


In [60]:
missing_positions = np.isnan(arr2d) | np.isinf(arr2d)
print(missing_positions)
arr2d[missing_positions] = -1
print(arr2d)
arr2d[1,1] = 5
arr2d[2,1] = 8
print(arr2d)

[[False False False]
 [False False False]
 [False False False]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [62]:
print(f"Mean: {arr2d.mean()}")
print(f"Min: {arr2d.min()}")
print(f"Max: {arr2d.max()}")

Mean: 5.0
Min: 1.0
Max: 9.0


In [63]:
print(np.amin(arr2d, axis=1))
print(np.amax(arr2d, axis=0))

[1. 4. 7.]
[7. 8. 9.]


In [66]:
arr = arr2d[:2, :2]
print(arr)
arr[0,0] = 10
print(arr)
print(arr2d)

[[10.  2.]
 [ 4.  5.]]
[[10.  2.]
 [ 4.  5.]]
[[10.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [69]:
arr = arr2d[:2, :2].copy()
arr[0, 0] = -10
print(arr)
print(arr2d)

[[-10.   2.]
 [  4.   5.]]
[[10.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]


In [76]:
arr2d = np.random.rand(3,4)*10
arr2d = arr2d.astype('int')
arr2d

array([[5, 3, 4, 4],
       [0, 9, 2, 3],
       [7, 9, 4, 8]])

In [85]:
# arr2d = arr2d.reshape(4, 3)
# print(arr2d)
arr2d.reshape(4,3)

array([[5, 3, 4],
       [4, 0, 9],
       [2, 3, 7],
       [9, 4, 8]])

In [90]:
arr2d.reshape(3,4)
print(arr2d.T)

[[5 4 2 9]
 [3 0 3 4]
 [4 9 7 8]]


In [91]:
a = arr2d.flatten()
b = arr2d.ravel()
print(a)
print(b)

[5 3 4 4 0 9 2 3 7 9 4 8]
[5 3 4 4 0 9 2 3 7 9 4 8]


In [92]:
a[0] = 1
print(arr2d)

[[5 3 4]
 [4 0 9]
 [2 3 7]
 [9 4 8]]


In [93]:
b[0] = 1
print(arr2d)

[[1 3 4]
 [4 0 9]
 [2 3 7]
 [9 4 8]]


.ravel() version returns a reference to the input ndarray, like the b above

In [94]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
np.arange(0,14)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [98]:
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [99]:
np.arange(10, 0, -1) # decreasing order

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [100]:
np.linspace(start=1, stop=50, num=10, dtype=int)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [101]:
np.linspace(1, 50)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [104]:
np.linspace(0, 100).size

50

In [105]:
# limit the number of digits
np.set_printoptions(precision=2)
np.logspace(start=1, stop=50, num=15, base=10)

array([1.00e+01, 3.16e+04, 1.00e+08, 3.16e+11, 1.00e+15, 3.16e+18,
       1.00e+22, 3.16e+25, 1.00e+29, 3.16e+32, 1.00e+36, 3.16e+39,
       1.00e+43, 3.16e+46, 1.00e+50])

In [107]:
np.logspace(start=1, stop=10, base=2, dtype=int)

array([   2,    2,    2,    2,    3,    3,    4,    4,    5,    6,    7,
          8,    9,   10,   11,   13,   15,   17,   19,   22,   25,   28,
         32,   37,   42,   48,   54,   62,   70,   80,   91,  103,  117,
        133,  151,  172,  195,  222,  252,  286,  325,  369,  420,  477,
        541,  615,  698,  793,  901, 1024])

np.tile() will repeat a whole list or array n times. Whereas np.repeat() repeats each item n times

In [111]:
a = np.array([1,2,3])
b = np.tile(a, 2)
print(b)
c = np.repeat(a, 2)
print(c)

[1 2 3 1 2 3]
[1 1 2 2 3 3]


In [112]:
# random number between [0, 1) with a shape of (2, 2)
print(np.random.rand(2,2))
# Normal distribution with mean=0 & std=1, a shape of (2, 2)
print(np.random.randn(2,2))

[[0.4  0.45]
 [0.03 0.57]]
[[-1.25  0.11]
 [ 0.49 -0.2 ]]


In [113]:
# Random integers between [0, 10) of shape 2,2
print(np.random.randint(0, 10, size=[2,2]))

# One random number between [0,1)
print(np.random.random())

# Random numbers between [0,1) of shape 2,2
print(np.random.random(size=[2,2]))

[[4 0]
 [0 3]]
0.7786460033163551
[[0.48 0.96]
 [0.15 0.65]]


In [116]:
# pick 10 items from an array with equal probabilities
print(np.random.choice(['h', 'e', 'l', 'l', 'o'], size=10))
# pick 10 items from an array with assigned probabilities
print(np.random.choice(['h', 'e', 'l', 'l', 'o'], size=10, p=[0.2,0.4,0.1,0.1,0.2]))

['o' 'e' 'l' 'l' 'l' 'e' 'e' 'h' 'e' 'e']
['h' 'e' 'e' 'e' 'h' 'e' 'o' 'o' 'h' 'l']


In [121]:
# if you want to generate exactly same numbers every time, set the seed
rn = np.random.RandomState(100)
print(rn.rand(2, 2))

[[0.54 0.28]
 [0.42 0.84]]


In [124]:
np.random.seed(100)
print(np.random.rand(2,2))


[[0.54 0.28]
 [0.42 0.84]]
[[0.   0.12]
 [0.67 0.83]]


In [126]:
arr = np.random.randint(0, 10, size=10)
arr

array([0, 9, 6, 2, 4, 1, 5, 3, 4, 4])

In [127]:
arr[1] = 6
arr[0] = 5
print(arr)

[5 6 6 2 4 1 5 3 4 4]


In [128]:
# get the unique items
unique, count = np.unique(arr, return_counts=True)
print(unique)
print(count)

[1 2 3 4 5 6]
[1 1 1 3 2 2]
